main/urls.py
from django.urls import path

from . import views

app_name = "web"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("user/", views.user_page, name="user"),
    path("<str:username>/approve/", views.approve, name="approve"),
    path("<str:username>/remove/", views.remove_user, name="remove_user"),
    path("update-account/", views.update_account, name="update_account"),
    path("new-post/", views.new_post, name="new-post"),
    path("add-post/", views.add_new_document, name="add-post"),
    path("cabinet/", views.show_documents, name="cabinet"),
    path("search/", views.search, name="search"),
    path("<str:filename>/sign/", views.sign, name="document_sign"),
    path("<str:filename>/edit/", views.edit_document, name="document_edit"),
    path("<str:filename>/cancel/", views.cancel, name="document_cancel"),
    path("<str:filename>/apply/", views.apply_edits, name="document_edit_apply"),
    path("<str:filename>/review/", views.review, name="document_review"),
    path("<str:filename>/review/new/", views.new_review, name="new_document_review"),
    path(
        "<str:filename>/review/download/", views.download, name="new_document_download"
    ),
]

server/urls.py
from django.contrib import admin
from django.urls import include, path

from main.views import my_404_handler, my_500_handler

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

handler404 = my_404_handler
handler500 = my_500_handler

templates/layouts/main_layout.html
<!DOCTYPE html>
{% load static %}
<html class="no-js h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
      {% block title %}
      {% endblock title %}
    | Howa resminama</title>
    <meta name="description"
          content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/svg" href="{% static "web/images/logo.svg" %}">
    <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          id="main-stylesheet"
          data-version="1.1.0"
          href="{% static 'web/styles/shards-dashboards.1.1.0.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'web/styles/extras.1.1.0.min.css' %}">
    <script async defer src="{% static 'web/scripts/buttons.js' %}"></script>
  </head>
  <body class="h-100">
    <div class="container-fluid">
      <div class="row">
        <!-- Main Sidebar -->
        <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
          <div class="main-navbar">
            <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
              <a class="navbar-brand w-100 mr-0"
                 href="{% url 'web:cabinet' %}"
                 style="line-height: 25px">
                <div class="d-table m-auto">
                  <img id="main-logo"
                       class="d-inline-block align-top mr-1"
                       style="max-width: 25px"
                       src="{% static 'web/images/logo.svg' %}">
                  <span class="d-none d-md-inline ml-1">Howa resminama</span>
                </div>
              </a>
              <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="fa fa-list"></i>
              </a>
            </nav>
          </div>
          <div class="nav-wrapper">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'web:cabinet' %}">
                  <i class="fa fa-pencil"></i>
                  <span>Esasy</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'web:new-post' %}">
                  <i class="fa-solid fa-file-circle-plus"></i>
                  <span>Resminama döretmek</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'web:user' %}">
                  <i class="fa fa-user-circle"></i>
                  <span>Profil</span>
                </a>
              </li>
            </ul>
          </div>
        </aside>
        <!-- End Main Sidebar -->
        <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
          <div class="main-navbar sticky-top bg-white">
            <!-- Main Navbar -->
            <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
              <form class="main-navbar__search w-100 d-none d-md-flex d-lg-flex"
                    method="post"
                    action="{% url 'web:search' %}">
                {% csrf_token %}
                <div class="input-group input-group-seamless ml-3">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="fas"></i>
                    </div>
                  </div>
                </div>
                <input class="navbar-search form-control"
                       type="text"
                       placeholder="Gözleg..."
                       name="text">
              </form>
              <!-- Уведомления -->
              <ul class="navbar-nav border-left flex-row ">
                <li class="nav-item border-right dropdown notifications">
                  <a class="nav-link nav-link-icon text-center"
                     href="#"
                     role="button"
                     id="dropdownMenuLink"
                     data-toggle="dropdown"
                     aria-haspopup="true"
                     aria-expanded="false">
                    <div class="nav-link-icon__wrapper">
                      <i class="fa fa-bell"></i>
                      {% if notifications %}<span class="badge badge-pill badge-danger">{{ notifications|length }}</span>{% endif %}
                    </div>
                  </a>
                  {% if notifications %}
                    {% for notification in notifications %}
                      <div class="dropdown-menu dropdown-menu-small"
                           aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="#">
                          <div class="notification__icon-wrapper">
                            <div class="notification__icon">
                              <i class="fa fa-bell"></i>
                            </div>
                          </div>
                          <div class="notification__content">
                            <p>{{ notification }}</p>
                          </div>
                        </a>
                      </div>
                    {% endfor %}
                  {% else %}
                    <div class="dropdown-menu dropdown-menu-small"
                         aria-labelledby="dropdownMenuLink">
                      <a class="dropdown-item" href="#">
                        <div class="notification__icon-wrapper">
                          <div class="notification__icon">
                            <i class="fa fa-bell"></i>
                          </div>
                        </div>
                        <div class="notification__content d-flex align-items-center">
                          <div>Täze habar ýok</div>
                        </div>
                      </a>
                    </div>
                  </li>
                {% endif %}
                <li class="nav-item dropdown d-flex align-items-center">
                  <a class="nav-link dropdown-toggle text-nowrap px-3"
                     data-toggle="dropdown"
                     href="#"
                     role="button"
                     aria-haspopup="true"
                     aria-expanded="false">
                    <span class="d-none d-md-inline-block"><i class="fa fa-user-circle"></i>{{ username }}</span>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right dropdown-menu-small">
                    <a class="dropdown-item text-danger" href="{% url 'web:logout' %}">
                      <i class="fa fa-sign-out text-danger"></i> Çykyş </a>
                  </div>
                </li>
              </ul>
              <nav class="nav">
                <a href="#"
                   class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left"
                   data-toggle="collapse"
                   data-target=".header-navbar"
                   aria-expanded="false"
                   aria-controls="header-navbar">
                  <i class="fa fa-list"></i>
                </a>
              </nav>
            </nav>
          </div>
          <!-- / .main-navbar -->
          <div class="main-content-container container-fluid px-4">
            {% block body %}
            {% endblock body %}
          </div>
          <footer class="main-footer d-flex p-2 px-3 bg-white border-top"
                  style="border-radius: 15px 15px 0 0">
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'web:cabinet' %}"><i class="fa fa-home"></i></a>
              </li>
            </ul>
            <span class="copyright ml-auto my-auto mr-2">Ähli hukuklar goralan © 2024</span>
          </footer>
        </main>
      </div>
    </div>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>