main/urls.py
from django.urls import path

from . import views

app_name = "web"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("user/", views.user_page, name="user"),
    path("<str:username>/approve/", views.approve, name="approve"),
    path("<str:username>/remove/", views.remove_user, name="remove_user"),
    path("update-account/", views.update_account, name="update_account"),
    path("new-post/", views.new_post, name="new-post"),
    path("add-post/", views.add_new_document, name="add-post"),
    path("cabinet/", views.show_documents, name="cabinet"),
    path("search/", views.search, name="search"),
    path("<str:filename>/sign/", views.sign, name="document_sign"),
    path("<str:filename>/edit/", views.edit_document, name="document_edit"),
    path("<str:filename>/cancel/", views.cancel, name="document_cancel"),
    path("<str:filename>/apply/", views.apply_edits, name="document_edit_apply"),
    path("<str:filename>/review/", views.review, name="document_review"),
    path("<str:filename>/review/new/", views.new_review, name="new_document_review"),
    path(
        "<str:filename>/review/download/", views.download, name="new_document_download"
    ),
]

server/urls.py
from django.contrib import admin
from django.urls import include, path

from main.views import my_404_handler, my_500_handler

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

handler404 = my_404_handler
handler500 = my_500_handler

main/models.py
from datetime import date, datetime, timedelta

from django.conf import settings
from django.contrib.auth.models import Group, User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here


class Document(models.Model):
    filename = models.CharField(max_length=200)
    filepath = models.FilePathField(path=settings.MEDIA_ROOT, null=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    description = models.TextField(null=True)
    signs_number = models.PositiveIntegerField(default=0)
    signed = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=25, default="Prosesde")

    def __str__(self):
        return self.filename


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    notifications = models.TextField(blank=True)
    approved = models.BooleanField(default=False)
    personal_files = models.ManyToManyField(Document, related_name="owner", blank=True)
    files_to_contrib = models.ManyToManyField(
        Document, related_name="reviewer", blank=True
    )

    def __str__(self):
        return str(self.user)

    def get_statistic(self):
        deadlines_count = 0
        personal_files = Document.objects.filter(
            owner__user__username=self.user.username
        )
        if not personal_files:
            personal_files = ""
        files_to_contrib = Document.objects.filter(
            reviewer__user__username=self.user.username
        ).filter(status="Prosesde")
        if files_to_contrib:
            for document in files_to_contrib:
                deadline = date.fromisoformat(str(document.date))
                if (
                    deadline - datetime.now().date() <= timedelta(days=1)
                    and document.status != "Taýýar"
                ):
                    deadlines_count += 1
        else:
            files_to_contrib = ""
        personal_context = {
            "deadlines": deadlines_count,
            "files_to_sign": len(files_to_contrib),
            "personal_files": len(personal_files),
            "my_files": personal_files,
            "review_files": files_to_contrib,
        }
        return personal_context

    def get_group_persons(self):
        persons = set()
        for group in self.user.groups.all():
            users = User.objects.filter(groups=Group.objects.get(name=group.name))
            for user in users:
                persons.add(user.username)
        return persons

    def get_notifications(self):
        notifications = str(self.notifications).split("\n")
        if notifications.count("") != 0:
            notifications.remove("")
        self.notifications = ""
        self.save()
        return notifications

    def update(self, username=None, email=None, password=None):
        if username:
            self.user.username = username
        if email:
            self.user.email = email
        if password:
            self.user.set_password(password)
        self.user.save()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main/views.py
import mimetypes
import os
from datetime import datetime
from pathlib import Path

from django.conf import settings
from django.contrib.auth import authenticate, get_user, login, logout
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import AnonymousUser, Group, User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .models import Document

extensions = [".pdf", ".docx"]


def index(request, alert=None):
    groups = Group.objects.all()
    context = {"companies": groups, "alert": alert}
    return render(request, "web/main.html", context=context)


def check_logged_in(request):
    user = get_user(request)
    if isinstance(user, AnonymousUser):
        return render(request, "web/errors.html", context={"errno": "403"})
    return user


def log_in(request):
    if request.method == "POST":
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        user = authenticate(username=username, password=password)
        if user is not None:
            if not user.profile.approved:
                context = {
                    "text": "Ulgam dolandyryjy hasabyňyzy tassyklaýança garaşmagyňyzy haýyş edýäris"
                }
                return render(request, "web/errors.html", context)
            login(request, user)
        else:
            context = {"text": "Ulanyjy ady we/ýa-da açar sözi nädogry"}
            return render(request, "web/errors.html", context)
        return redirect("web:cabinet")
    context = {"text": "Täzeden girmäge synanyşyň"}
    return render(request, "web/errors.html", context)


def log_out(request):
    logout(request)
    return redirect("web:index")


def signup(request):
    if request.method != "POST":
        return render(request, "web/errors.html", context={"errno": "403"})
    username = request.POST.get("username")
    email = request.POST.get("email")
    password = request.POST.get("password")
    group_name = request.POST.get("select-company")
    user_exists = User.objects.filter(username=username).count() != 0
    email_exists = User.objects.filter(email=email).count() != 0
    if user_exists:
        return index(request, alert="Berlen atda ulanyjy hasaba alynan")
    if email_exists:
        return index(request, alert="Berlen E-Mailda ulanyjy hasaba alynan")
    group = Group.objects.get(name=group_name)
    user = User.objects.create_user(username=username, email=email, password=password)
    login(request, user)
    user.groups.set([group])
    user.profile.notifications = ""
    user.profile.approved = False
    user.save()
    return redirect("web:index")


def new_post(request):
    user = get_user(request)
    notifications = user.profile.get_notifications()
    persons = user.profile.get_group_persons()
    context = {
        "username": user.username,
        "notifications": notifications,
        "persons": persons,
    }
    return render(request, "web/add-new-post.html", context)


def user_directory_path(user):
    return "{0}/user_{1}/".format(settings.MEDIA_ROOT, user.id)


def handle_uploaded_file(user, file, filename):
    path = user_directory_path(user)
    Path(path).mkdir(parents=True, exist_ok=True)
    with open(path + filename, "wb+") as destination:
        for chunk in file.chunks():
            destination.write(chunk)


def delete_old_file(user, filename):
    path = user_directory_path(user) + filename
    Path(path).unlink(missing_ok=True)


def notify_users(request, text, document):
    recipient_counter = 1
    signs_number = 0
    while True:
        recipient = request.POST.get("selectUser-" + str(recipient_counter))
        recipient_counter += 1
        if recipient is None:
            break
        if str(recipient) == "Ulanyjyny saýlaň":
            continue
        signs_number += 1
        # Добавить получателям файл в список файлов на подписание
        rec = User.objects.get(username=recipient)
        # Вписываем уведомления пользователя
        rec_notifications = str(rec.profile.notifications)
        rec_notifications += text.format(document.filename)
        rec.profile.notifications = rec_notifications
        rec.profile.files_to_contrib.add(document)
        rec.save()
    return signs_number


def add_new_document(request):
    if request.method != "POST":
        return render(request, "web/errors.html", context={"errno": "403"})
    user = check_logged_in(request)
    ext = request.FILES.get("file").name.split(".")[-1]
    filename = str(request.POST.get("Filename")).replace(" ", "") + "." + ext
    description = request.POST.get("description")
    if str(description) == "<br>" or str(description) == "":
        description = "Düşündiriş ýok"
    deadline = request.POST.get("Date")
    filepath = user_directory_path(user)
    d = Document.objects.create(
        filename=filename,
        filepath=filepath,
        date=deadline,
        description=description,
        user=user,
    )
    user.profile.personal_files.add(d)
    user.save()
    path = user_directory_path(user) + filename
    d.signs_number = notify_users(request, "{} faýly tassyklama sanawyna girizildi", d)
    d.signed = 0
    d.save()
    handle_uploaded_file(user, request.FILES.get("file"), filename)
    # setup file in order to lately use it
    # Creator.create(path_to_file=path, user_id=str(user.id), primary=True)
    return redirect("web:cabinet")


def my_404_handler(request, exception):
    context = {"errno": "404"}
    return render(request, "web/errors.html", context)


def my_500_handler(request):
    context = {"errno": "500"}
    return render(request, "web/errors.html", context)


def csrf_failure(request, reason=""):
    context = {"errno": "403", "text": reason}
    return render(request, "web/errors.html", context)


def review(request, filename):
    user = get_user(request)
    notifications = user.profile.get_notifications()
    personal_context = user.profile.get_statistic()
    file = Document.objects.filter(filename=filename).filter(
        Q(owner__user__username=user.username)
        | Q(reviewer__user__username=user.username)
    )[0]
    owner = file.owner.all()[0]
    reviewer = (
        User.objects.filter(username=user.username)
        .filter(profile__files_to_contrib=file.id)
        .count()
        != 0
    )
    path = user_directory_path(owner) + filename
    if "/app" in path:
        path = path.replace("/app", ".")
    # sd = Creator.create(user_id=str(user.id), path_to_file=path, primary=False)
    if owner.id == user.id:
        # signs = [User.objects.get(id=sign_id) for sign_id in sd.who_signed()]
        pass
    else:
        signs = None
    context = {
        "username": user.username,
        "filename": filename,
        "file_date": file.date,
        "description": file.description,
        "owner": owner.id == user.id,
        "reviewer": reviewer,
        "status": str(file.status),
        # "signed": sd.who_signed().count(str(user.id)) != 0,
        # "signs": signs,
        "notifications": notifications,
    }
    context.update(personal_context)
    return render(request, "web/document_review.html", context)


def new_review(request, filename):
    author = get_user(request)
    username = author.username
    description = request.POST.get("description")
    publish_date = datetime.now().date()
    document = Document.objects.filter(filename=filename).filter(
        Q(owner__user__username=username) | Q(reviewer__user__username=username)
    )[0]
    return redirect("web:document_review", filename)


def download(request, filename):
    file_obj = Document.objects.get(filename=filename)
    file = user_directory_path(file_obj.uploaded_by) + filename
    with open(file, "rb") as f:
        response = HttpResponse(f.read())
        file_type = mimetypes.guess_type(file)
        if file_type is None:
            file_type = "application/octet-stream"
        response["Content-Type"] = file_type
        response["Content-Length"] = str(os.stat(file).st_size)
        response["Content-Disposition"] = f"attachment; filename={filename}"
    return response


def user_page(request):
    user = check_logged_in(request)
    notifications = user.profile.get_notifications()
    context = {
        "username": user.username,
        "email": user.email,
        "notifications": notifications,
    }
    return render(request, "web/user-profile-lite.html", context=context)


def update_account(request):
    user = check_logged_in(request)
    username = request.POST.get("username")
    email = request.POST.get("email")
    password = request.POST.get("password")
    user.profile.update(username, email, password)
    notifications = user.profile.get_notifications()
    context = {
        "username": username,
        "email": user.email,
        "notifications": notifications,
    }
    return render(request, "web/user-profile-lite.html", context=context)


def show_documents(request):
    user = get_user(request)
    notifications = user.profile.get_notifications()
    personal_context = user.profile.get_statistic()
    context = {"username": user.username, "notifications": notifications}
    context.update(personal_context)
    return render(request, "web/tables.html", context=context)


def search(request):
    user = get_user(request)
    notifications = user.profile.get_notifications()
    text = request.POST.get("text")
    personal_context = user.profile.get_statistic()
    files_found = [
        Document.objects.filter(filename=text + ext).filter(
            Q(owner__user__username=user.username)
            | Q(reviewer__user__username=user.username)
        )
        for ext in extensions
    ]
    context = {
        "username": user.username,
        "notifications": notifications,
        "files_found": files_found,
    }
    context.update(personal_context)

templates/web/document_review.html
{% extends "layouts/main_layout.html" %}
{% load static %}
{% block title %}
  Resminamany gözden geçirmek
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static 'quill/css/quill.snow.css' %}">
{% endblock head %}
{% block body %}
  <div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
      <span class="text-uppercase page-subtitle"></span>
      <h3 class="page-title">Resminamany gözden geçirmek</h3>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg col-md-6 col-sm-6 mb-4">
        <div class="stats-small stats-small--1 card card-small">
          <div class="card-body p-0 d-flex">
            <div class="d-flex flex-column m-auto">
              <div class="stats-small__data text-center">
                <span class="stats-small__label text-uppercase">Ýakynda möhleti dolýanlar</span>
                <h6 class="stats-small__value count my-3">{{ deadlines }}</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg col-md-6 col-sm-6 mb-4">
        <div class="stats-small stats-small--1 card card-small">
          <div class="card-body p-0 d-flex">
            <div class="d-flex flex-column m-auto">
              <div class="stats-small__data text-center">
                <span class="stats-small__label text-uppercase">Tassyklanmalylar</span>
                <h6 class="stats-small__value count my-3">{{ files_to_sign }}</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg col-md-4 col-sm-6 mb-4">
        <div class="stats-small stats-small--1 card card-small">
          <div class="card-body p-0 d-flex">
            <div class="d-flex flex-column m-auto">
              <div class="stats-small__data text-center">
                <span class="stats-small__label text-uppercase">Meniň resminamalarym</span>
                <h6 class="stats-small__value count my-3">{{ personal_files }}</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Small Stats Blocks -->
    <div class="row">
      <!-- Discussions Component -->
      <div class="col-lg-9 col-md-12 col-sm-12 mb-4">
        <!-- Post Overview -->
        <div class='card card-small mb-3'>
          <div class="card-header border-bottom">
            <h6 class="m-0">Resminama barada giňişleýin</h6>
          </div>
          <div class='card-body p-0'>
            <ul class="list-group list-group-flush">
              <li class="list-group-item p-3">
                <span class="d-flex mb-2">
                  <strong class="mr-1">Ady:</strong> {{ filename }}
                  {#                          <a class="ml-auto" href="{% url 'web:new_document_download' filename %}">Download</a>#}
                  <button class="btn btn-sm btn-accent ml-auto"
                          id="publishButton"
                          onclick="window.location.href='{% url "web:new_document_download" filename %}';">
                    Ýüklemek
                  </button>
                </span>
                <span class="d-flex mb-2">
                  <strong class="mr-1">Möhleti:</strong>{{ file_date }}
                </span>
                <span class="d-flex mb-2">
                  <strong class="mr-1">Ýagdaýy:</strong>
                  {% if status == 'Prosesde' %}
                    <strong class="text-warning">{{ status }}</strong>
                  {% else %}
                    {% if status == "Ret edildi" %}
                      <strong class="text-danger">{{ status }}</strong>
                    {% else %}
                      <strong class="text-success">{{ status }}</strong>
                    {% endif %}
                  {% endif %}
                </span>
                {% if owner %}
                  {% for sign in signs %}
                    <span class="d-flex mb-2">
                      <strong class="mr-1">{{ sign }}</strong>
                      <strong class="text-success">Tassyklanan</strong>
                    </span>
                  {% endfor %}
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-12">
        <!-- Post Overview -->
        <div class='card card-small mb-3'>
          <div class="card-header border-bottom">
            <h6 class="m-0">Kararlar</h6>
          </div>
          <div class="card-header border-bottom mx-auto">
            {% if owner %}
              <input type="button"
                     class="mb-2 btn btn-primary mr-1"
                     value="Üýtgetmek"
                     onclick="window.location.href='{% url "web:document_edit" filename %}';">
            {% endif %}
            {% if reviewer and not signed %}
              <input type="button"
                     class="mb-2 btn btn-success mr-2"
                     value="Tassyklamak"
                     onclick="window.location.href='{% url "web:document_sign" filename %}';">
              <input type="button"
                     class="mb-2 btn btn-danger mr-2"
                     value="Ret etmek"
                     onclick="window.location.href='{% url "web:document_cancel" filename %}';">
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock body %}
{% block scripts %}
  {% include "shortcuts/default_scripts.html" %}
  <script src="{% static 'quill/js/quill.min.js' %}"></script>
  <script src="{% static 'web/scripts/app/app-blog-new-post.1.1.0.js' %}"></script>
  <script src="{% static 'web/scripts/app/app-blog-overview.1.1.0.js' %}"></script>
  <script src="{% static 'web/scripts/app/app-register-form-validation.js' %}"></script>
{% endblock scripts %}

templates/web/main.html
<!DOCTYPE html>
{% load static %}
<html class="no-js h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
      {% block title %}
      {% endblock title %}
    Giriş | Howa resminama</title>
    <meta name="description"
          content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon"
          type="image/png"
          href="{% static "favicon.ico" %}">
    <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          id="main-stylesheet"
          data-version="1.1.0"
          href="{% static 'web/styles/shards-dashboards.1.1.0.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'web/styles/extras.1.1.0.min.css' %}">
    <script async defer src="{% static 'web/scripts/buttons.js' %}"></script>
  </head>
  <body class="h-100">
    <div class="container">
      {% if alert %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <i class="fa fa-info mx-2 my-2"></i>
          {{ alert }}
        </div>
      {% endif %}
      <div class="main-content-container container-fluid px-4">
        <div class=" row my-5"
             style="display: flex;
                    flex-direction: column;
                    justify-content: center">
          <div class="col-lg-8 mx-auto" id="loginForm">
            <div class="card card-small mb-4">
              <div class="card-header border-bottom">
                <h6 class="m-0">Awtorizasiýa</h6>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item p-3">
                  <div class="row">
                    <div class="col-sm-12">
                      <form method="post" action="{% url 'web:login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                          <div class="input-group mb-3">
                            <div class="input-group-prepend">
                              <span class="input-group-text" id="basic-addon1">@</span>
                            </div>
                            <input type="text"
                                   name="username"
                                   class="form-control"
                                   placeholder="Ulanyjy ady"
                                   aria-label="Username"
                                   aria-describedby="basic-addon1">
                          </div>
                        </div>
                        <div class="form-group">
                          <input type="password"
                                 name="password"
                                 class="form-control"
                                 id="inputPassword4"
                                 placeholder="Açar sözi"
                                 value="">
                        </div>
                        <div class="form-group">
                          <button type="submit"
                                  class="mb-2 btn btn-outline-primary mr-2"
                                  id="loginButton">Giriş</button>
                        </div>
                        <div id="registered" style="display: flex;">
                          <h6 class="p-2">Şahşy hasabyňyz ýokmy?</h6>
                          <a class="p-2" href="javascript:switchForms();">Registrasiýa</a>
                          {#                                <a class="p-2">or</a>#}
                          {#                              <a class="p-2" href="javascript:registerCompany();">Register company</a>#}
                        </div>
                      </form>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-8 mx-auto" style="display: none;" id="registerForm">
            <div class="card card-small mb-4">
              <div class="card-header border-bottom">
                <h6 class="m-0">Registrasiýa</h6>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item p-3">
                  <div class="row">
                    <div class="col-sm-12">
                      <form onsubmit="return formValidation();"
                            method="post"
                            action="{% url 'web:signup' %}">
                        {% csrf_token %}
                        <div class="form-group">
                          <div class="input-group mb-3">
                            <input type="text"
                                   class="form-control"
                                   name="username"
                                   placeholder="Ulanyjy ady"
                                   aria-label="Username"
                                   aria-describedby="basic-addon1"
                                   id="registerUsername">
                          </div>
                        </div>
                        <small class="errorReq" style="display: none; color: red" id="errorUsername"><i></i> Ulanyjy adyňyzy giriziň </small>
                        <div class="form-group">
                          <div class="input-group mb-3">
                            <div class="input-group-prepend">
                              <span class="input-group-text" id="basic-addon1">@</span>
                            </div>
                            <input type="text"
                                   class="form-control"
                                   name="email"
                                   placeholder="E-mail"
                                   aria-label="Username"
                                   aria-describedby="basic-addon1"
                                   id="registerEmail">
                          </div>
                        </div>
                        <small class="errorReq"  style="display: none; color: red;" id="errorEmail"><i></i> Nädogry E-Mail </small>
                        <div class="form-group">
                          <input type="password"
                                 class="form-control"
                                 name="password"
                                 id="registerInputPassword"
                                 placeholder="Açar sözi"
                                 value="">
                        </div>
                        <small class="errorReq"  style="display: none; color: red;" id="errorPass"><i></i> Açar sözler deň gelenok</small>
                        <div class="form-group">
                          <input type="password"
                                 class="form-control"
                                 id="repeatPassword"
                                 placeholder="Açar sözüni gaýtalaň"
                                 value="">
                        </div>
                        <div class="form-group" id="Select company dropdown">
                          <select class="custom-select custom-select-sm"
                                  style="max-width: 130px"
                                  id="selectCompany"
                                  name="select-company">
                            <option selected>Bölüm</option>
                            {% if companies %}
                              {% for company in companies %}<option value="{{ company }}">{{ company }}</option>{% endfor %}
                            {% endif %}
                          </select>
                          <small class="errorReq"  style="display: none; color: red;" id="errorSelect"><i></i> Bölümi saýlaň</small>
                        </div>
                        <div class="form-group">
                          <button type="submit" class="mb-2 btn btn-outline-primary mr-2">Registasiýa</button>
                        </div>
                        <div id="loginHint" style="display: none;">
                          <h6 class="p-2">Eýýäm registasiýany geçdiňizmi?</h6>
                          <a class="p-2" href="javascript:switchForms();">Giriş</a>
                        </div>
                      </form>
                    </div>
                  </form>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'web/scripts/app/app-register-form-validation.js' %}"></script>
</body>
</html>